### ISSUE TITLE
fresh install db error

### ISSUE THREAD

**Issue by namen3645** [Shroud-email/shroud.email#35]
```
root@mail-ml1-f01:~/hosting# docker compose up -d
WARN[0000] The "SENTRY_DSN" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_YEARLY_PRICE" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_MONTHLY_PRICE" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_WEBHOOK_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "NOTIFIER_WEBHOOK_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_OCTOPUS_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_OCTOPUS_LIST_ID" variable is not set. Defaulting to a blank string.
[+] Running 45/45
⠿ caddy Pulled 6.9s
⠿ a0d0a0d46f8b Pull complete 1.2s
⠿ a9d9d63a262e Pull complete 1.5s
⠿ b1d54a459a50 Pull complete 1.6s
⠿ 8e7c08047a89 Pull complete 3.9s
⠿ 480638d00096 Pull complete 4.2s
⠿ e4a34fe0f845 Pull complete 5.2s
⠿ db Pulled 71.2s
⠿ 5034a66b99e6 Pull complete 39.6s
⠿ 82e9eb77798b Pull complete 40.4s
⠿ c6b2245b2f36 Pull complete 68.5s
⠿ ccd761727716 Pull complete 68.7s
⠿ 3da258773353 Pull complete 68.8s
⠿ 2c7ee7bc69e8 Pull complete 68.9s
⠿ 028554d3b6cc Pull complete 69.0s
⠿ spamassassin Pulled 70.9s
⠿ 3e731ddb7fc9 Pull complete 59.3s
⠿ f2385fc3f78f Pull complete 67.5s
⠿ c5a9e8d34744 Pull complete 67.9s
⠿ 6dc415c828d6 Pull complete 68.3s
⠿ 20a7d7308be9 Pull complete 68.6s
⠿ 1e5ef12ebc63 Pull complete 68.9s
⠿ dfb125bb575f Pull complete 69.1s
⠿ haraka Pulled 50.7s
⠿ 2408cc74d12b Pull complete 4.1s
⠿ 8283096dcba0 Pull complete 16.1s
⠿ a3e654983208 Pull complete 16.5s
⠿ 024c9a3b77d6 Pull complete 16.6s
⠿ bb759177a4c9 Pull complete 32.4s
⠿ 17b9f7359246 Pull complete 32.9s
⠿ f025adb87c1e Pull complete 47.5s
⠿ 8920ec0dac32 Pull complete 48.1s
⠿ 296977a973b5 Pull complete 48.6s
⠿ web Pulled 63.5s
⠿ f8416d8bac72 Pull complete 33.4s
⠿ 75fb8fbbd8d8 Pull complete 37.2s
⠿ 424219053566 Pull complete 50.3s
⠿ e8eb7a94033c Pull complete 51.6s
⠿ 34392001a08a Pull complete 52.5s
⠿ aea24e7e7bd6 Pull complete 52.8s
⠿ 8a04ca9d2d6c Pull complete 53.2s
⠿ fad2798eb9dd Pull complete 53.5s
⠿ 4c230bfdbea9 Pull complete 54.1s
⠿ 5893ef84a97b Pull complete 54.4s
⠿ 8d91d8f02e79 Pull complete 61.7s
[+] Building 1.2s (11/11) FINISHED
=> [internal] load build definition from Dockerfile 0.1s
=> => transferring dockerfile: 324B 0.0s
=> [internal] load .dockerignore 0.0s
=> => transferring context: 2B 0.0s
=> [internal] load metadata for docker.io/library/alpine:3.15 1.1s
=> [1/6] FROM docker.io/library/alpine:3.15@sha256:cf34c62ee8eb3fe8aa24c1fab45d7e9d12768d945c3f5a6fd6a63d901e898479 0.0s
=> [internal] load build context 0.0s
=> => transferring context: 2.30kB 0.0s
=> CACHED [2/6] RUN apk update && apk add --no-cache bash 0.0s
=> CACHED [3/6] WORKDIR /workdir 0.0s
=> CACHED [4/6] COPY lets-encrypt-r4.pem /workdir/lets-encrypt-r4.pem 0.0s
=> CACHED [5/6] COPY bundle_certs.sh /etc/periodic/daily/bundle_certs 0.0s
=> CACHED [6/6] RUN chmod +x /etc/periodic/daily/bundle_certs 0.0s
=> exporting to image 0.0s
=> => exporting layers 0.0s
=> => writing image sha256:d6d7d5c9aad8448b3fcf1aae4a3fff18134a0fdda4d3312ec65cbc82c094029a 0.0s
=> => naming to docker.io/library/hosting-cron 0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 6/6
⠿ Container hosting-spamassassin-1 Started 2.7s
⠿ Container hosting-caddy-1 Started 3.1s
⠿ Container hosting-cron-1 Started 2.9s
⠿ Container hosting-db-1 Started 3.1s
⠿ Container hosting-haraka-1 Started 4.0s
⠿ Container hosting-web-1 Started 5.1s
root@mail-ml1-f01:~/hosting# docker compose logs -f
WARN[0000] The "SENTRY_DSN" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_YEARLY_PRICE" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_MONTHLY_PRICE" variable is not set. Defaulting to a blank string.
WARN[0000] The "STRIPE_WEBHOOK_SECRET" variable is not set. Defaulting to a blank string.
WARN[0000] The "NOTIFIER_WEBHOOK_URL" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_OCTOPUS_API_KEY" variable is not set. Defaulting to a blank string.
WARN[0000] The "EMAIL_OCTOPUS_LIST_ID" variable is not set. Defaulting to a blank string.
hosting-web-1 | + /home/elixir/app/bin/shroud eval Shroud.Release.migrate
hosting-web-1 | 23:58:35.391 [error] Postgrex.Protocol (#PID<0.136.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
hosting-web-1 | 23:58:35.391 [error] Postgrex.Protocol (#PID<0.135.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
hosting-web-1 | 23:58:37.048 [error] Postgrex.Protocol (#PID<0.135.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
hosting-web-1 | 23:58:37.578 [error] Postgrex.Protocol (#PID<0.136.0>) failed to connect: ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "postgres"
hosting-web-1 | 23:58:38.091 [error] Could not create schema migrations table. This error usually happens due to the following:
hosting-web-1 |
hosting-web-1 | * The database does not exist
hosting-web-1 | * The "schema_migrations" table, which Ecto uses for managing
hosting-web-1 | migrations, was defined by another library
hosting-web-1 | * There is a deadlock while migrating (such as using concurrent
hosting-web-1 | indexes with a migration_lock)
hosting-web-1 |
hosting-web-1 | To fix the first issue, run "mix ecto.create".
hosting-web-1 |
hosting-web-1 | To address the second, you can run "mix ecto.drop" followed by
hosting-web-1 | "mix ecto.create". Alternatively you may configure Ecto to use
hosting-web-1 | another table and/or repository for managing migrations:
hosting-web-1 |
hosting-web-1 | config :shroud, Shroud.Repo,
hosting-web-1 | migration_source: "some_other_table_for_schema_migrations",
hosting-web-1 | migration_repo: AnotherRepoForSchemaMigrations
hosting-web-1 |
hosting-web-1 | The full error report is shown below.
hosting-web-1 |
hosting-web-1 | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2900ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
hosting-web-1 |
hosting-web-1 | 1. Ensuring your database is available and that you can connect to it
hosting-web-1 | 2. Tracking down slow queries and making sure they are running fast enough
hosting-web-1 | 3. Increasing the pool_size (although this increases resource consumption)
hosting-web-1 | 4. Allowing requests to wait longer by increasing :queue_target and :queue_interval
hosting-web-1 |
hosting-web-1 | See DBConnection.start_link/2 for more information
hosting-web-1 |
hosting-web-1 | (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
hosting-web-1 | (elixir 1.13.2) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
hosting-web-1 | (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1024: Ecto.Adapters.SQL.execute_ddl/4
hosting-web-1 | (ecto_sql 3.8.3) lib/ecto/migrator.ex:696: Ecto.Migrator.verbose_schema_migration/3
hosting-web-1 | (ecto_sql 3.8.3) lib/ecto/migrator.ex:510: Ecto.Migrator.lock_for_migrations/4
hosting-web-1 | (ecto_sql 3.8.3) lib/ecto/migrator.ex:422: Ecto.Migrator.run/4
hosting-web-1 | (ecto_sql 3.8.3) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
hosting-web-1 | (shroud 0.1.0) lib/shroud/release.ex:12: anonymous fn/2 in Shroud.Release.migrate/0
hosting-web-1 | + /home/elixir/app/bin/shroud eval Shroud.Release.migrate
hosting-db-1 |
hosting-db-1 | PostgreSQL Database directory appears to contain a database; Skipping initialization
hosting-db-1 |
hosting-db-1 | 2022-12-11 23:58:30.042 UTC [1] LOG: starting PostgreSQL 14.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
hosting-db-1 | 2022-12-11 23:58:30.049 UTC [1] LOG: listening on IPv4 address "0.0.0.0", port 5432
hosting-db-1 | 2022-12-11 23:58:30.050 UTC [1] LOG: listening on IPv6 address "::", port 5432
hosting-db-1 | 2022-12-11 23:58:30.055 UTC [1] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
hosting-db-1 | 2022-12-11 23:58:30.065 UTC [20] LOG: database system was shut down at 2022-12-11 23:44:30 UTC
hosting-db-1 | 2022-12-11 23:58:30.075 UTC [1] LOG: database system is ready to accept connections
hosting-db-1 | 2022-12-11 23:58:35.357 UTC [27] FATAL: password authentication failed for user "postgres"
hosting-db-1 | 2022-12-11 23:58:35.357 UTC [27] DETAIL: Role "postgres" does not exist.
hosting-db-1 | Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
hosting-db-1 | 2022-12-11 23:58:35.361 UTC [28] FATAL: password authentication failed for user "postgres"
hosting-db-1 | 2022-12-11 23:58:35.361 UTC [28] DETAIL: Role "postgres" does not exist.
hosting-db-1 | Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
hosting-db-1 | 2022-12-11 23:58:37.046 UTC [29] FATAL: password authentication failed for user "postgres"
hosting-db-1 | 2022-12-11 23:58:37.046 UTC [29] DETAIL: Role "postgres" does not exist.
hosting-db-1 | Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
hosting-db-1 | 2022-12-11 23:58:37.576 UTC [30] FATAL: password authentication failed for user "postgres"
hosting-db-1 | 2022-12-11 23:58:37.576 UTC [30] DETAIL: Role "postgres" does not exist.
hosting-db-1 | Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```

**Comment by taobojlen** [comment]
closing in favor of https://github.com/Shroud-email/hosting/issues/6
